import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";
import test, { after, before, beforeEach } from "node:test";
import mysql, { type Connection } from "mysql2/promise";

const testDatabaseUrl = process.env.TEST_DATABASE_URL;
if (!testDatabaseUrl || !new URL(testDatabaseUrl).pathname.slice(1).endsWith("_test")) throw new Error("Set TEST_DATABASE_URL to an isolated MySQL database ending in _test");
const sourceUrl = new URL(testDatabaseUrl); const freshDatabase = `workbench_fin02_fresh_${process.pid}_test`; const upgradeDatabase = `workbench_fin02_upgrade_${process.pid}_test`; const migrationDirectory = resolve(process.cwd(), "../../db/migration");
let admin: Connection; let pool: Awaited<typeof import("../src/db/index.js")>["pool"]; let app: Awaited<typeof import("../src/app.js")>["app"]; let signToken: Awaited<typeof import("../src/auth.js")>["signToken"]; let counter = 0; const op = () => `94000000-0000-4000-8000-${String(++counter).padStart(12, "0")}`;
function version(name: string) { const match = /^V(\d+)(?:_(\d+))?__/.exec(name)!; return [Number(match[1]), Number(match[2] ?? 0)]; }
async function migrations() { return (await readdir(migrationDirectory)).filter((name) => /^V\d+(?:_\d+)?__.*\.sql$/.test(name)).sort((a, b) => version(a)[0] - version(b)[0] || version(a)[1] - version(b)[1] || a.localeCompare(b)); }
async function migrate(connection: Connection, database: string, from = 1, through = 31) { await connection.query(`USE \`${database}\``); for (const name of await migrations()) { const major = version(name)[0]; if (major >= from && major <= through) await connection.query(await readFile(resolve(migrationDirectory, name), "utf8")); } }
function headers(userId = 1) { return { Authorization: `Bearer ${signToken({ id: userId, username: `fin02-${userId}`, displayName: `FIN02 ${userId}` })}`, "Content-Type": "application/json" }; }
async function api<T>(path: string, init: RequestInit = {}, userId = 1) { const response = await app.request(`/api${path}`, { ...init, headers: { ...headers(userId), ...(init.headers ?? {}) } }); const body = await response.json() as { data: T; message: string }; return { response, data: body.data, message: body.message }; }
async function scalar(sql: string, values: unknown[] = []) { const [rows] = await pool.query(sql, values); return Number(Object.values((rows as Record<string, unknown>[])[0])[0]); }
async function initialize(userId = 1) { return api<{ categoryCount: number }>("/finance/initialize", { method: "POST", body: JSON.stringify({ operationId: op() }) }, userId); }
async function categories(userId = 1) { return (await api<Array<{ id: number; name: string; kind: string; enabled: boolean; version: number }>>("/finance/categories", {}, userId)).data; }
async function account(input: Record<string, unknown> = {}, userId = 1) { return api<{ id: number; version: number; balanceCents: string }>("/finance/accounts", { method: "POST", body: JSON.stringify({ operationId: op(), name: `账户-${counter}`, type: "BANK", openingDate: "2026-09-21", openingBalanceCents: "0", includeInOverview: true, ...input }) }, userId); }
async function expense(accountId: number, categoryId: number, amountCents = "10000", userId = 1) { return api<{ transactionId: number; version: number }>("/finance/expenses", { method: "POST", body: JSON.stringify({ operationId: op(), accountId, categoryId, amountCents, occurredDate: "2026-09-21", occurredTime: "10:00", note: "FIN02 expense" }) }, userId); }
async function transfer(sourceAccountId: number, targetAccountId: number, extra: Record<string, unknown> = {}, operationId = op()) { return api<{ transactionId: number; feeTransactionId: number | null }>("/finance/transfers", { method: "POST", body: JSON.stringify({ operationId, sourceAccountId, targetAccountId, amountCents: "12000", occurredDate: "2026-09-21", occurredTime: "11:00", ...extra }) }); }

before(async () => {
  admin = await mysql.createConnection({ host: sourceUrl.hostname, port: Number(sourceUrl.port || 3306), user: decodeURIComponent(sourceUrl.username), password: decodeURIComponent(sourceUrl.password), multipleStatements: true, timezone: "Z" });
  await admin.query(`CREATE DATABASE \`${freshDatabase}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`); await admin.query(`CREATE DATABASE \`${upgradeDatabase}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await migrate(admin, freshDatabase); await migrate(admin, upgradeDatabase, 1, 28); await admin.query(`USE \`${upgradeDatabase}\``); await admin.query("INSERT INTO quick_notes (user_id,note_date,content,created_at,updated_at) VALUES (1,'2026-09-20','preserve FIN02',NOW(),NOW())"); await migrate(admin, upgradeDatabase, 29, 31);
  const appUrl = new URL(testDatabaseUrl); appUrl.pathname = `/${freshDatabase}`; process.env.NODE_ENV = "test"; process.env.DATABASE_URL = appUrl.toString(); process.env.JWT_SECRET = "fin02-tests-only-secret"; [{ pool }, { app }, { signToken }] = await Promise.all([import("../src/db/index.js"), import("../src/app.js"), import("../src/auth.js")]);
});
beforeEach(async () => { await pool.query("UPDATE finance_transactions SET related_transaction_id=NULL, source_account_id=NULL, target_account_id=NULL"); for (const table of ["finance_entries", "finance_transactions", "finance_accounts", "finance_categories", "mutation_receipts"]) await pool.query(`DELETE FROM ${table}`); await pool.query("UPDATE users SET deleted_at=NULL,timezone='Asia/Shanghai' WHERE id=1"); });
after(async () => { await pool?.end(); await admin.query(`DROP DATABASE IF EXISTS \`${freshDatabase}\``); await admin.query(`DROP DATABASE IF EXISTS \`${upgradeDatabase}\``); await admin.end(); });

test("V29 migrates fresh and upgrades V28 without changing history", async () => {
  const [columns] = await admin.query(`SELECT column_name FROM information_schema.columns WHERE table_schema='${freshDatabase}' AND table_name='finance_transactions' AND column_name IN ('source_account_id','target_account_id','related_transaction_id')`); assert.equal((columns as unknown[]).length, 3);
  await admin.query(`USE \`${upgradeDatabase}\``); const [notes] = await admin.query("SELECT content FROM quick_notes WHERE content='preserve FIN02'"); assert.equal((notes as unknown[]).length, 1);
});

test("transfer is one header, two entries, zero flow, and replay-safe", async () => {
  const source = await account({ name: "现金", openingBalanceCents: "50000" }); const target = await account({ name: "银行卡" }); const operationId = op(); const first = await transfer(source.data.id, target.data.id, {}, operationId); const replay = await transfer(source.data.id, target.data.id, {}, operationId);
  assert.equal(first.response.status, 200); assert.equal(await scalar("SELECT COUNT(*) FROM finance_transactions WHERE type=3"), 1); assert.equal(await scalar("SELECT COUNT(*) FROM finance_entries WHERE transaction_id=?", [first.data.transactionId]), 2); const accounts = await api<Array<{ id: number; balanceCents: string }>>("/finance/accounts"); assert.deepEqual(accounts.data.map((item) => [item.id, item.balanceCents]), [[source.data.id, "38000"], [target.data.id, "12000"]]); const overview = await api<{ monthlyIncomeCents: string; monthlyExpenseCents: string }>("/finance/overview?month=2026-09"); assert.deepEqual([overview.data.monthlyIncomeCents, overview.data.monthlyExpenseCents], ["0", "0"]); const list = await api<{ items: Array<{ type: string; displayAmountCents: string; sourceAccountName: string; targetAccountName: string }> }>("/finance/transactions"); const transferItem = list.data.items.find((item) => item.type === "TRANSFER")!; assert.deepEqual([transferItem.displayAmountCents, transferItem.sourceAccountName, transferItem.targetAccountName], ["12000", "现金", "银行卡"]); const detail = await api<{ displayAmountCents: string; transfer: { amountCents: string; sourceAccountName: string; targetAccountName: string } }>(`/finance/transactions/${first.data.transactionId}`); assert.deepEqual([detail.data.displayAmountCents, detail.data.transfer.amountCents, detail.data.transfer.sourceAccountName, detail.data.transfer.targetAccountName], ["12000", "12000", "现金", "银行卡"]); assert.equal(replay.response.status, 200); assert.equal(await scalar("SELECT COUNT(*) FROM finance_transactions WHERE type=3"), 1);
});

test("transfer fee is a linked expense and credit repayment remains transfer", async () => {
  await initialize(); const feeCategory = (await categories()).find((item) => item.kind === "EXPENSE")!; const source = await account({ name: "主账户", openingBalanceCents: "50000" }); const credit = await account({ name: "信用卡", type: "CREDIT" }); const result = await transfer(source.data.id, credit.data.id, { feeAmountCents: "300", feeCategoryId: feeCategory.id }); assert.equal(result.response.status, 200); assert.equal(result.data.feeTransactionId !== null, true); const overview = await api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-09"); assert.equal(overview.data.monthlyExpenseCents, "300"); const list = await api<{ items: Array<{ type: string; amountCents: string }> }>("/finance/transactions"); assert.deepEqual(list.data.items.map((item) => item.type), ["EXPENSE", "TRANSFER", "OPENING"]); assert.equal(list.data.items.find((item) => item.type === "TRANSFER")?.amountCents, "0");
});

test("partial refund is cumulative, bounded, and retains the original category history", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const source = await account({ openingBalanceCents: "50000" }); const posted = await expense(source.data.id, category.id, "10000"); const first = await api<{ transactionId: number; remainingRefundableCents: string }>(`/finance/transactions/${posted.data.transactionId}/refunds`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: posted.data.version, amountCents: "4000", occurredDate: "2026-09-21", occurredTime: "12:00" }) }); assert.equal(first.response.status, 200); const second = await api<{ remainingRefundableCents: string }>(`/finance/transactions/${posted.data.transactionId}/refunds`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 2, amountCents: "6000", occurredDate: "2026-09-21", occurredTime: "12:30" }) }); assert.equal(second.response.status, 200); const over = await api(`/finance/transactions/${posted.data.transactionId}/refunds`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 3, amountCents: "1", occurredDate: "2026-09-21", occurredTime: "12:40" }) }); assert.equal(over.response.status, 409); await pool.query("UPDATE finance_categories SET enabled=0 WHERE id=?", [category.id]); const detail = await api<{ categoryName: string }>(`/finance/transactions/${first.data.transactionId}`); assert.equal(detail.data.categoryName, category.name); const overview = await api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-09"); assert.equal(overview.data.monthlyExpenseCents, "0");
});

test("correction preserves original and void appends a reversal", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const source = await account({ openingBalanceCents: "50000" }); const posted = await expense(source.data.id, category.id, "10000"); const corrected = await api<{ reversalTransactionId: number; transactionId: number }>(`/finance/transactions/${posted.data.transactionId}/correct`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: posted.data.version, amountCents: "7000", accountId: source.data.id, categoryId: category.id, occurredDate: "2026-09-21", occurredTime: "13:00" }) }); assert.equal(corrected.response.status, 200); assert.equal(await scalar("SELECT status FROM finance_transactions WHERE id=?", [posted.data.transactionId]), 1); assert.equal(await scalar("SELECT COUNT(*) FROM finance_transactions WHERE related_transaction_id=?", [posted.data.transactionId]), 2); const other = await expense(source.data.id, category.id, "2000"); const voided = await api<{ originalTransactionId: number }>(`/finance/transactions/${other.data.transactionId}/void`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: other.data.version, occurredDate: "2026-09-21", occurredTime: "13:30" }) }); assert.equal(voided.response.status, 200); assert.equal(await scalar("SELECT status FROM finance_transactions WHERE id=?", [other.data.transactionId]), 2); const overview = await api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-09"); assert.equal(overview.data.monthlyExpenseCents, "7000");
});

test("finance read DTO exposes display amounts and product-facing relation summaries", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const source = await account({ name: "来源", openingBalanceCents: "50000" }); const target = await account({ name: "目标" }); const transferResult = await transfer(source.data.id, target.data.id, { amountCents: "12000" }); const transferList = await api<{ items: Array<{ type: string; displayAmountCents: string; sourceAccountName: string; targetAccountName: string }> }>("/finance/transactions"); const transferItem = transferList.data.items.find((item) => item.type === "TRANSFER")!; assert.deepEqual([transferItem.displayAmountCents, transferItem.sourceAccountName, transferItem.targetAccountName], ["12000", "来源", "目标"]); const transferDetail = await api<{ transfer: { amountCents: string; sourceAccountName: string; targetAccountName: string } }>(`/finance/transactions/${transferResult.data.transactionId}`); assert.deepEqual([transferDetail.data.transfer.amountCents, transferDetail.data.transfer.sourceAccountName, transferDetail.data.transfer.targetAccountName], ["12000", "来源", "目标"]);
  const posted = await expense(source.data.id, category.id, "10000"); const refund = await api(`/finance/transactions/${posted.data.transactionId}/refunds`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: posted.data.version, amountCents: "3000", occurredDate: "2026-09-22", occurredTime: "12:00" }) }); assert.equal(refund.response.status, 200); const refundSummary = await api<{ refund: { originalAmountCents: string; refundedAmountCents: string; remainingRefundableCents: string; canRefund: boolean } }>(`/finance/transactions/${posted.data.transactionId}`); assert.deepEqual([refundSummary.data.refund.originalAmountCents, refundSummary.data.refund.refundedAmountCents, refundSummary.data.refund.remainingRefundableCents, refundSummary.data.refund.canRefund], ["10000", "3000", "7000", true]);
  const corrected = await api<{ transactionId: number }>(`/finance/transactions/${posted.data.transactionId}/correct`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 2, amountCents: "4000", accountId: target.data.id, categoryId: category.id, occurredDate: "2026-09-22", occurredTime: "12:30" }) }); const correction = await api<{ correction: { original: { id: number; status: string }; current: { id: number; amountCents: string } } }>(`/finance/transactions/${posted.data.transactionId}`); assert.deepEqual([correction.data.correction.original.id, correction.data.correction.original.status, correction.data.correction.current.id, correction.data.correction.current.amountCents], [posted.data.transactionId, "已更正", corrected.data.transactionId, "-4000"]);
});

test("terminal finance records expose no refundable remainder", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const source = await account({ name: "终态账户", openingBalanceCents: "50000" });
  const correctedSource = await expense(source.data.id, category.id, "10000"); await api(`/finance/transactions/${correctedSource.data.transactionId}/refunds`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1, amountCents: "3000", occurredDate: "2026-09-23", occurredTime: "12:00" }) }); await api(`/finance/transactions/${correctedSource.data.transactionId}/correct`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 2, amountCents: "4000", accountId: source.data.id, categoryId: category.id, occurredDate: "2026-09-23", occurredTime: "12:30" }) });
  const corrected = await api<{ status: string; refund: { refundedAmountCents: string; remainingRefundableCents: string; canRefund: boolean } }>(`/finance/transactions/${correctedSource.data.transactionId}`); assert.deepEqual([corrected.data.status, corrected.data.refund.refundedAmountCents, corrected.data.refund.remainingRefundableCents, corrected.data.refund.canRefund], ["REVERSED", "3000", "0", false]);
  const voidedSource = await expense(source.data.id, category.id, "5000");
  await api(`/finance/transactions/${voidedSource.data.transactionId}/void`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1, occurredDate: "2026-09-23", occurredTime: "13:00" }) });
  const voided = await api<{ status: string; refund: { remainingRefundableCents: string; canRefund: boolean } }>(`/finance/transactions/${voidedSource.data.transactionId}`);
  assert.deepEqual([voided.data.status, voided.data.refund.remainingRefundableCents, voided.data.refund.canRefund], ["VOIDED", "0", false]);
});

test("archive excludes new writes but preserves account balance and supports unarchive", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const source = await account({ openingBalanceCents: "10000" }); const direct = await api(`/finance/accounts/${source.data.id}/archive`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: source.data.version }) }); assert.equal(direct.response.status, 200); assert.equal((await expense(source.data.id, category.id)).response.status, 409); const all = await api<Array<{ id: number; archivedAt: string | null; balanceCents: string }>>("/finance/accounts?view=all"); assert.equal(all.data[0].balanceCents, "10000"); const restored = await api(`/finance/accounts/${source.data.id}/unarchive`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 2 }) }); assert.equal(restored.response.status, 200);
});

test("transfer operation failure rolls back header, entries, and receipt", async () => {
  const source = await account({ openingBalanceCents: "10000" }); const target = await account(); const operationId = op(); await pool.query("CREATE TRIGGER fail_finance_entry_insert BEFORE INSERT ON finance_entries FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced FIN02 entry failure'"); const failed = await api(`/finance/transfers`, { method: "POST", body: JSON.stringify({ operationId, sourceAccountId: source.data.id, targetAccountId: target.data.id, amountCents: "1000", occurredDate: "2026-09-21", occurredTime: "14:00" }) }); await pool.query("DROP TRIGGER fail_finance_entry_insert"); assert.equal(failed.response.status, 500); assert.equal(await scalar("SELECT COUNT(*) FROM finance_transactions"), 1); assert.equal(await scalar("SELECT COUNT(*) FROM finance_entries"), 1); assert.equal(await scalar("SELECT COUNT(*) FROM mutation_receipts WHERE operation_id=?", [operationId]), 0);
});
