import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";
import { after, before, beforeEach, test } from "node:test";
import mysql, { type Connection, type Pool } from "mysql2/promise";

const sourceUrl = process.env.TEST_DATABASE_URL;
if (!sourceUrl || !new URL(sourceUrl).pathname.slice(1).endsWith("_test")) throw new Error("Set TEST_DATABASE_URL to an isolated MySQL database ending in _test");
const source = new URL(sourceUrl);
const fresh = `workbench_fin03_edges_${process.pid}_test`;
const migrationDirectory = resolve(process.cwd(), "../../db/migration");
let admin: Connection; let pool: Pool; let app: typeof import("../src/app.js").app; let signToken: typeof import("../src/auth.js").signToken; let token = ""; let sequence = 0;
function version(name: string) { const match = /^V(\d+)(?:_(\d+))?__/.exec(name)!; return [Number(match[1]), Number(match[2] ?? 0)]; }
async function migrations() { return (await readdir(migrationDirectory)).filter((name) => /^V\d+(?:_\d+)?__.*\.sql$/.test(name)).sort((a, b) => version(a)[0] - version(b)[0] || version(a)[1] - version(b)[1] || a.localeCompare(b)); }
async function migrate(connection: Connection) { await connection.query(`USE \`${fresh}\``); for (const name of await migrations()) await connection.query(await readFile(resolve(migrationDirectory, name), "utf8")); }
async function api<T = unknown>(path: string, init: RequestInit = {}) { const response = await app.request(`http://localhost/api${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...(init.headers ?? {}) } }); const body = await response.json() as { data: T; code: number; message: string }; return { response, data: body.data }; }
function op() { return `${sequence++}-0000-4000-8000-000000000000`.replace(/^\d+/, (value) => value.padStart(8, "0")); }
async function scalar(query: string, values: unknown[] = []) { const [rows] = await pool.query(query, values); return Number((rows as Array<Record<string, unknown>>)[0].value); }
async function initialize() { await api("/finance/initialize", { method: "POST", body: JSON.stringify({ operationId: op() }) }); }
async function account(name: string) { return api<{ id: number; version: number }>("/finance/accounts", { method: "POST", body: JSON.stringify({ operationId: op(), name: `${name}-${sequence}`, type: "BANK", openingDate: "2026-01-01", openingBalanceCents: "0", includeInOverview: true }) }); }
async function expense(accountId: number, categoryId: number, amountCents: string, occurredDate: string) { return api<{ id: number; version: number }>("/finance/expenses", { method: "POST", body: JSON.stringify({ operationId: op(), accountId, categoryId, amountCents, occurredDate, occurredTime: "12:00" }) }); }
async function categories() { return (await api<Array<{ id: number; kind: string }>>("/finance/categories")).data; }
async function createTemplate(input: Record<string, unknown>) { return api<{ id: number; version: number }>("/finance/recurring-templates", { method: "POST", body: JSON.stringify({ operationId: op(), type: "EXPENSE", name: "edge template", amountCents: "1000", frequency: "MONTHLY", scheduleValue: 5, startDate: "2026-01-01", ...input }) }); }
async function prepare(from: string, to: string) { return api<{ created: number }>("/finance/recurring-occurrences/prepare", { method: "POST", body: JSON.stringify({ operationId: op(), from, to }) }); }

before(async () => { admin = await mysql.createConnection({ host: source.hostname, port: Number(source.port || 3306), user: decodeURIComponent(source.username), password: decodeURIComponent(source.password), multipleStatements: true, timezone: "Z" }); await admin.query(`CREATE DATABASE \`${fresh}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`); await migrate(admin); const appUrl = new URL(sourceUrl); appUrl.pathname = `/${fresh}`; process.env.DATABASE_URL = appUrl.toString(); process.env.JWT_SECRET = "fin03-edge-tests-only-secret"; [{ pool }, { app }, { signToken }] = await Promise.all([import("../src/db/index.js"), import("../src/app.js"), import("../src/auth.js")]); token = signToken({ id: 1, username: "test", displayName: "Test" }); });
beforeEach(async () => { await pool.query("DROP TRIGGER IF EXISTS fail_fin03_entry_insert"); await pool.query("SET FOREIGN_KEY_CHECKS=0"); for (const table of ["finance_recurring_occurrences", "finance_recurring_templates", "finance_budgets", "finance_entries", "finance_transactions", "finance_accounts", "finance_categories", "mutation_receipts"]) await pool.query(`DELETE FROM ${table}`); await pool.query("SET FOREIGN_KEY_CHECKS=1"); await pool.query("UPDATE users SET deleted_at=NULL,timezone='Asia/Shanghai' WHERE id=1"); });
after(async () => { await pool?.end(); await admin.query(`DROP DATABASE IF EXISTS \`${fresh}\``); await admin.end(); });

test("cross-month refund and correction use one effective-flow rule in overview, budget and report", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const sourceAccount = await account("cross-month");
  const original = await expense(sourceAccount.data.id, category.id, "10000", "2026-08-15");
  await api(`/finance/transactions/${original.data.id}/refunds`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1, amountCents: "3000", occurredDate: "2026-09-02", occurredTime: "12:00" }) });
  await api("/finance/budgets", { method: "POST", body: JSON.stringify({ operationId: op(), budgetMonth: "2026-08", limitCents: "20000" }) });
  await api("/finance/budgets", { method: "POST", body: JSON.stringify({ operationId: op(), budgetMonth: "2026-09", limitCents: "20000" }) });
  const [augOverview, sepOverview, augBudget, sepBudget, augReport, sepReport] = await Promise.all([
    api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-08"), api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-09"), api<Array<{ spentCents: string }>>("/finance/budgets?month=2026-08"), api<Array<{ spentCents: string }>>("/finance/budgets?month=2026-09"), api<{ monthly: { expenseCents: string } }>("/finance/reports?month=2026-08"), api<{ monthly: { expenseCents: string } }>("/finance/reports?month=2026-09")
  ]);
  assert.deepEqual([augOverview.data.monthlyExpenseCents, augBudget.data[0].spentCents, augReport.data.monthly.expenseCents], ["10000", "10000", "10000"]);
  assert.deepEqual([sepOverview.data.monthlyExpenseCents, sepBudget.data[0].spentCents, sepReport.data.monthly.expenseCents], ["-3000", "-3000", "-3000"]);
});

test("cross-month correction leaves original month and records net adjustment in correction month", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const sourceAccount = await account("correction"); const original = await expense(sourceAccount.data.id, category.id, "10000", "2026-08-15");
  await api(`/finance/transactions/${original.data.id}/correct`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1, amountCents: "4000", occurredDate: "2026-09-03", occurredTime: "12:00" }) });
  await api("/finance/budgets", { method: "POST", body: JSON.stringify({ operationId: op(), budgetMonth: "2026-08", limitCents: "20000" }) }); await api("/finance/budgets", { method: "POST", body: JSON.stringify({ operationId: op(), budgetMonth: "2026-09", limitCents: "20000" }) });
  const [augOverview, sepOverview, augBudget, sepBudget, augReport, sepReport] = await Promise.all([api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-08"), api<{ monthlyExpenseCents: string }>("/finance/overview?month=2026-09"), api<Array<{ spentCents: string }>>("/finance/budgets?month=2026-08"), api<Array<{ spentCents: string }>>("/finance/budgets?month=2026-09"), api<{ monthly: { expenseCents: string } }>("/finance/reports?month=2026-08"), api<{ monthly: { expenseCents: string } }>("/finance/reports?month=2026-09")]);
  assert.deepEqual([augOverview.data.monthlyExpenseCents, augBudget.data[0].spentCents, augReport.data.monthly.expenseCents], ["10000", "10000", "10000"]); assert.deepEqual([sepOverview.data.monthlyExpenseCents, sepBudget.data[0].spentCents, sepReport.data.monthly.expenseCents], ["-6000", "-6000", "-6000"]);
});

test("monthly day 31 uses month end, weekly uses weekday, and endDate stops occurrences", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const sourceAccount = await account("dates");
  const monthly = await createTemplate({ accountId: sourceAccount.data.id, categoryId: category.id, frequency: "MONTHLY", scheduleValue: 31, startDate: "2026-01-01" });
  const weekly = await createTemplate({ accountId: sourceAccount.data.id, categoryId: category.id, frequency: "WEEKLY", scheduleValue: 1, startDate: "2026-04-01", endDate: "2026-04-20" });
  await prepare("2026-02-01", "2028-02-29");
  const monthlyRows = (await api<Array<{ templateId: number; scheduledDate: string }>>("/finance/recurring-occurrences?from=2026-02-01&to=2028-02-29")).data.filter((row) => row.templateId === monthly.data.id).map((row) => row.scheduledDate);
  assert.ok(monthlyRows.includes("2026-02-28")); assert.ok(monthlyRows.includes("2026-04-30")); assert.ok(monthlyRows.includes("2028-02-29"));
  await prepare("2026-04-01", "2026-04-30"); const weeklyRows = (await api<Array<{ templateId: number; scheduledDate: string }>>("/finance/recurring-occurrences?from=2026-04-01&to=2026-04-30")).data.filter((row) => row.templateId === weekly.data.id).map((row) => row.scheduledDate);
  assert.deepEqual(weeklyRows, ["2026-04-06", "2026-04-13", "2026-04-20"]);
});

test("GET is pure and prepare is idempotent under the unique template/date key", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const sourceAccount = await account("prepare"); await createTemplate({ accountId: sourceAccount.data.id, categoryId: category.id, scheduleValue: 5, startDate: "2026-09-01" });
  const before = [await scalar("SELECT COUNT(*) value FROM finance_recurring_occurrences"), await scalar("SELECT COUNT(*) value FROM mutation_receipts")]; await api("/finance/recurring-templates"); await api("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30"); const afterGet = [await scalar("SELECT COUNT(*) value FROM finance_recurring_occurrences"), await scalar("SELECT COUNT(*) value FROM mutation_receipts")]; assert.deepEqual(afterGet, before);
  assert.equal((await prepare("2026-09-01", "2026-09-30")).data.created, 1); assert.equal((await prepare("2026-09-01", "2026-09-30")).data.created, 0); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_recurring_occurrences"), 1); assert.equal(await scalar("SELECT COUNT(DISTINCT index_name) value FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='finance_recurring_occurrences' AND index_name='uk_finance_recurring_occurrence_date'"), 1);
});

test("confirm replay, changed payload conflict, and transaction failure rollback are explicit", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const sourceAccount = await account("confirm"); await createTemplate({ accountId: sourceAccount.data.id, categoryId: category.id, scheduleValue: 5, startDate: "2026-09-01" }); await prepare("2026-09-01", "2026-09-30"); const occurrence = (await api<Array<{ id: number; version: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data[0]; const operationId = op();
  const first = await api<{ transactionId: number }>(`/finance/recurring-occurrences/${occurrence.id}/confirm`, { method: "POST", body: JSON.stringify({ operationId, expectedVersion: 1, occurredTime: "09:00" }) }); const replay = await api<{ transactionId: number }>(`/finance/recurring-occurrences/${occurrence.id}/confirm`, { method: "POST", body: JSON.stringify({ operationId, expectedVersion: 1, occurredTime: "09:00" }) }); const changed = await api(` /finance/recurring-occurrences/${occurrence.id}/confirm`.trim(), { method: "POST", body: JSON.stringify({ operationId, expectedVersion: 1, occurredTime: "10:00" }) });
  assert.equal(first.response.status, 200); assert.equal(replay.response.status, 200); assert.equal(replay.data.transactionId, first.data.transactionId); assert.equal(changed.response.status, 409); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_transactions"), 1); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_entries"), 1);
  const secondTemplate = await createTemplate({ accountId: sourceAccount.data.id, categoryId: category.id, scheduleValue: 12, startDate: "2026-09-01" }); await prepare("2026-09-01", "2026-09-30"); const pending = (await api<Array<{ id: number; version: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data.find((row) => row.id !== occurrence.id)!; const receiptsBeforeFailure = await scalar("SELECT COUNT(*) value FROM mutation_receipts"); await pool.query("CREATE TRIGGER fail_fin03_entry_insert BEFORE INSERT ON finance_entries FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced FIN03 entry failure'"); const failed = await api(`/finance/recurring-occurrences/${pending.id}/confirm`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: pending.version }) }); await pool.query("DROP TRIGGER fail_fin03_entry_insert"); assert.equal(failed.response.status, 500); const pendingAfter = (await api<Array<{ status: string }>>(`/finance/recurring-occurrences?from=2026-09-12&to=2026-09-12`)).data[0]; assert.equal(pendingAfter.status, "PENDING"); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_transactions"), 1); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_entries"), 1); assert.equal(await scalar("SELECT COUNT(*) value FROM mutation_receipts"), receiptsBeforeFailure);
  assert.equal(secondTemplate.response.status, 200);
});

test("posted and skipped snapshots stay immutable while future pending stays frozen", async () => {
  await initialize(); const expenseCategories = (await categories()).filter((item) => item.kind === "EXPENSE"); const firstAccount = await account("history-a"); const secondAccount = await account("history-b"); const template = await createTemplate({ accountId: firstAccount.data.id, categoryId: expenseCategories[0].id, amountCents: "1000", scheduleValue: 5, startDate: "2026-09-01" }); await prepare("2026-09-01", "2026-09-30"); const posted = (await api<Array<{ id: number; version: number; amountCentsSnapshot: string; accountIdSnapshot: number; categoryIdSnapshot: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data[0]; await api(`/finance/recurring-occurrences/${posted.id}/confirm`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: posted.version }) });
  const edit = await api<{ version: number }>(`/finance/recurring-templates/${template.data.id}`, { method: "PUT", body: JSON.stringify({ operationId: op(), expectedVersion: 1, amountCents: "2000", accountId: secondAccount.data.id, categoryId: expenseCategories[1].id, scheduleValue: 12 }) }); assert.equal(edit.response.status, 200); await prepare("2026-09-01", "2026-09-30"); const skipped = (await api<Array<{ id: number; version: number; scheduledDate: string; amountCentsSnapshot: string; accountIdSnapshot: number; categoryIdSnapshot: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data.find((row) => row.scheduledDate === "2026-09-12")!; await api(`/finance/recurring-occurrences/${skipped.id}/skip`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: skipped.version }) });
  const pendingTemplate = await api<{ version: number }>(`/finance/recurring-templates/${template.data.id}`, { method: "PUT", body: JSON.stringify({ operationId: op(), expectedVersion: 2, amountCents: "3000", accountId: firstAccount.data.id, categoryId: expenseCategories[0].id, scheduleValue: 20 }) }); assert.equal(pendingTemplate.response.status, 200); await prepare("2026-09-01", "2026-09-30"); const future = (await api<Array<{ id: number; version: number; scheduledDate: string; amountCentsSnapshot: string; accountIdSnapshot: number; categoryIdSnapshot: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data.find((row) => row.scheduledDate === "2026-09-20")!; await api(`/finance/recurring-templates/${template.data.id}`, { method: "PUT", body: JSON.stringify({ operationId: op(), expectedVersion: 3, amountCents: "4000", accountId: secondAccount.data.id, categoryId: expenseCategories[1].id, scheduleValue: 21 }) });
  const rows = (await api<Array<{ scheduledDate: string; status: string; amountCentsSnapshot: string; accountIdSnapshot: number; categoryIdSnapshot: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data; const postedAfter = rows.find((row) => row.scheduledDate === "2026-09-05")!; const skippedAfter = rows.find((row) => row.scheduledDate === "2026-09-12")!; const futureAfter = rows.find((row) => row.scheduledDate === "2026-09-20")!;
  assert.deepEqual([postedAfter.status, postedAfter.amountCentsSnapshot, postedAfter.accountIdSnapshot, postedAfter.categoryIdSnapshot], ["POSTED", "1000", firstAccount.data.id, expenseCategories[0].id]); assert.deepEqual([skippedAfter.status, skippedAfter.amountCentsSnapshot, skippedAfter.accountIdSnapshot, skippedAfter.categoryIdSnapshot], ["SKIPPED", "2000", secondAccount.data.id, expenseCategories[1].id]); assert.deepEqual([futureAfter.status, futureAfter.amountCentsSnapshot, futureAfter.accountIdSnapshot, futureAfter.categoryIdSnapshot], ["PENDING", "3000", firstAccount.data.id, expenseCategories[0].id]);
});

test("archived account and disabled category reject pending posting without ledger effects", async () => {
  await initialize(); const category = (await categories()).find((item) => item.kind === "EXPENSE")!; const sourceAccount = await account("invalid-post"); await createTemplate({ accountId: sourceAccount.data.id, categoryId: category.id, scheduleValue: 5, startDate: "2026-09-01" }); await prepare("2026-09-01", "2026-09-30"); const pending = (await api<Array<{ id: number; version: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data[0]; await api(`/finance/accounts/${sourceAccount.data.id}/archive`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1 }) }); const archived = await api(`/finance/recurring-occurrences/${pending.id}/confirm`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1 }) }); assert.equal(archived.response.status, 409);
  const second = await account("invalid-category"); const secondCategory = (await categories()).find((item) => item.kind === "EXPENSE" && item.id !== category.id)!; await createTemplate({ accountId: second.data.id, categoryId: secondCategory.id, scheduleValue: 12, startDate: "2026-09-01" }); await prepare("2026-09-01", "2026-09-30"); const pendingCategory = (await api<Array<{ id: number; version: number }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data.find((row) => row.id !== pending.id)!; await api(`/finance/categories/${secondCategory.id}`, { method: "PUT", body: JSON.stringify({ expectedVersion: 1, enabled: false }) }); const disabled = await api(`/finance/recurring-occurrences/${pendingCategory.id}/confirm`, { method: "POST", body: JSON.stringify({ operationId: op(), expectedVersion: 1 }) }); assert.equal(disabled.response.status, 409);
  const rows = (await api<Array<{ id: number; status: string }>>("/finance/recurring-occurrences?from=2026-09-01&to=2026-09-30")).data; assert.equal(rows.find((row) => row.id === pending.id)?.status, "PENDING"); assert.equal(rows.find((row) => row.id === pendingCategory.id)?.status, "PENDING"); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_transactions"), 0); assert.equal(await scalar("SELECT COUNT(*) value FROM finance_entries"), 0);
});
