import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, Eye, EyeOff, LogOut, Save } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import type { Request } from "../../app/api";
import { Badge, Button } from "../../shared/ui";

type Category = { id: number; name: string; color: string; dimensionKey: string; targetMinutes: number; enabled: number };
export type SettingsSnapshot = { profile: { id: number; username: string; displayName: string; timezone: string }; appearance: { theme: "light"; reducedMotion: boolean }; rewards: { show: boolean }; continuation: { mode: "manual"; automaticAvailable: false }; categories: Category[] };
type ExportFormat = "json" | "csv" | "markdown";
type ExportPayload = { fileName: string; contentType: string; recordCount: number; content: string };

export function useSettings(request: Request, userId: number) { return useQuery({ queryKey: ["settings", userId], queryFn: () => request<SettingsSnapshot>("/api/settings") }); }

export function SettingsFeature({ request, userId, logout, onProfileChanged, onError }: { request: Request; userId: number; logout: () => void; onProfileChanged: (profile: SettingsSnapshot["profile"]) => void; onError: (message: string, title?: string) => void }) {
  const queryClient = useQueryClient();
  const query = useSettings(request, userId);
  const [displayName, setDisplayName] = useState("");
  const [timezone, setTimezone] = useState("");
  const [pending, setPending] = useState(false);
  useEffect(() => { if (query.data) { setDisplayName(query.data.profile.displayName); setTimezone(query.data.profile.timezone); } }, [query.data]);
  async function patch(values: Record<string, unknown>) { const updated = await request<SettingsSnapshot>("/api/settings", { method: "PATCH", body: JSON.stringify(values) }); queryClient.setQueryData(["settings", userId], updated); onProfileChanged(updated.profile); return updated; }
  async function saveProfile(event: FormEvent) { event.preventDefault(); setPending(true); try { await patch({ displayName: displayName.trim(), timezone }); } catch (error) { onError(message(error), "设置没有保存"); } finally { setPending(false); } }
  async function toggleCategory(category: Category) { try { await request(`/api/task-categories/${category.id}`, { method: "PUT", body: JSON.stringify({ enabled: !category.enabled }) }); await Promise.all([query.refetch(), queryClient.invalidateQueries({ queryKey: ["today", userId] }), queryClient.invalidateQueries({ queryKey: ["tasks", userId] })]); } catch (error) { onError(message(error), "分类没有更新"); } }
  if (query.isPending) return <section className="settings-route"><p className="route-state">正在加载设置...</p></section>;
  if (!query.data || query.isError) return <section className="settings-route"><div className="notes-error"><p>{query.error instanceof Error ? query.error.message : "设置加载失败"}</p><Button onClick={() => void query.refetch()}>重试</Button></div></section>;
  const data = query.data;
  return <section className="settings-route"><header className="route-panel-heading"><div><p className="route-eyebrow">个人工作台</p><h1>设置</h1><p>偏好只影响新的记录和本地展示。</p></div></header><div className="settings-grid"><section className="settings-section"><h2>个人资料</h2><form className="settings-form" onSubmit={saveProfile}><label>显示名<input className="field" maxLength={64} value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label>时区<input className="field" list="timezone-options" value={timezone} onChange={(event) => setTimezone(event.target.value)} /><datalist id="timezone-options"><option value="Asia/Shanghai" /><option value="Asia/Tokyo" /><option value="Europe/London" /><option value="America/New_York" /><option value="UTC" /></datalist></label><p className="settings-note">新的记录将使用此时区；已有历史日期不会重新归属。</p><Button variant="primary" loading={pending} type="submit"><Save size={15} />保存资料</Button></form></section><section className="settings-section"><h2>任务与成长映射</h2><p className="settings-note">停用不会删除历史任务或投入快照；新建任务不再展示已停用分类。</p><div className="settings-category-list">{data.categories.map((category) => <div key={category.id}><i style={{ background: category.color }} /><span><strong>{category.name}</strong><small>{dimensionLabel(category.dimensionKey)} · 目标 {Math.round(category.targetMinutes / 60)} 小时</small></span><Button size="sm" onClick={() => void toggleCategory(category)}>{category.enabled ? "停用" : "启用"}</Button></div>)}</div></section><section className="settings-section"><h2>外观</h2><p className="settings-note">当前使用工作台浅色主题。</p><Toggle checked={data.appearance.reducedMotion} label="减少动效" onChange={async (checked) => { try { await patch({ reducedMotion: checked }); } catch (error) { onError(message(error)); } }} /></section><section className="settings-section"><h2>奖励展示</h2><Toggle checked={data.rewards.show} label="显示奖励界面" icon={data.rewards.show ? <Eye size={16} /> : <EyeOff size={16} />} onChange={async (checked) => { try { await patch({ showRewards: checked }); } catch (error) { onError(message(error)); } }} /><p className="settings-note">隐藏只改变界面展示，不会停止奖励结算。</p></section><section className="settings-section"><h2>续接</h2><div className="settings-line"><span><strong>手动决定</strong><small>未完成项由你选择续接、延后或忽略。</small></span><Badge tone="success">当前</Badge></div><p className="settings-note">自动续接尚未开放；现有显式命令不会被后台任务替代。</p></section><section className="settings-section"><h2>集成</h2><p className="settings-note">当前没有已配置的外部集成。Workbench 不会把 Web 登录凭据共享给第三方。</p></section><section className="settings-section settings-data"><h2>数据导出</h2><p className="settings-note">导出只在你主动触发时生成并下载；默认不包含回收站。</p><ExportRows request={request} onError={onError} /><p className="settings-note">导入功能将在后续 Data 阶段提供。</p></section><section className="settings-section"><h2>会话</h2><p className="settings-note">当前账号：{data.profile.username}</p><Button variant="danger" onClick={logout}><LogOut size={15} />退出登录</Button></section></div></section>;
}

function Toggle({ checked, label, icon, onChange }: { checked: boolean; label: string; icon?: React.ReactNode; onChange: (checked: boolean) => void }) { return <label className="settings-toggle">{icon}<span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
function ExportRows({ request, onError }: { request: Request; onError: (message: string, title?: string) => void }) { const rows: Array<{ domain: string; label: string; formats: ExportFormat[] }> = [{ domain: "tasks", label: "任务", formats: ["json", "csv"] }, { domain: "writing", label: "个人文字", formats: ["json", "csv", "markdown"] }, { domain: "calendar", label: "日历与时间", formats: ["json", "csv"] }, { domain: "rewards", label: "奖励记录", formats: ["json", "csv"] }, { domain: "life", label: "睡眠与饮水", formats: ["json", "csv"] }]; const [includeTrash, setIncludeTrash] = useState(false); return <div className="export-list"><label className="settings-toggle"><span>包括回收站</span><input type="checkbox" checked={includeTrash} onChange={(event) => setIncludeTrash(event.target.checked)} /></label>{rows.map((row) => <ExportRow key={row.domain} {...row} includeTrash={includeTrash} request={request} onError={onError} />)}</div>; }
function ExportRow({ domain, label, formats, includeTrash, request, onError }: { domain: string; label: string; formats: ExportFormat[]; includeTrash: boolean; request: Request; onError: (message: string, title?: string) => void }) { const [format, setFormat] = useState<ExportFormat>(formats[0]); const [pending, setPending] = useState(false); const [result, setResult] = useState<string | null>(null); async function run() { setPending(true); setResult(null); try { const payload = await request<ExportPayload>(`/api/exports/${domain}?format=${format}&includeTrash=${includeTrash}`); const blob = new Blob([payload.content], { type: `${payload.contentType};charset=utf-8` }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = payload.fileName; anchor.click(); URL.revokeObjectURL(url); setResult(`${payload.recordCount} 条`); } catch (error) { onError(message(error), "导出失败"); } finally { setPending(false); } } return <div className="export-row"><span><strong>{label}</strong>{result ? <small>{result}</small> : null}</span><select aria-label={`${label}导出格式`} value={format} onChange={(event) => setFormat(event.target.value as ExportFormat)}>{formats.map((item) => <option key={item} value={item}>{item === "markdown" ? "Markdown" : item.toUpperCase()}</option>)}</select><Button size="sm" loading={pending} onClick={() => void run()}><Download size={14} />导出</Button></div>; }
function dimensionLabel(value: string) { return ({ career: "事业力", creative: "创造力", learning: "学习力", life: "生活力", body: "身体力", social: "社交力", leisure: "兴趣成长", foundation: "基础状态" } as Record<string, string>)[value] ?? value; }
function message(error: unknown) { return error instanceof Error ? error.message : "操作失败"; }
