CREATE TABLE finance_budgets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  budget_month CHAR(7) NOT NULL,
  period_timezone VARCHAR(64) NOT NULL,
  category_id BIGINT UNSIGNED NULL,
  category_scope_key VARCHAR(32) NOT NULL,
  limit_cents BIGINT NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uk_finance_budget_scope (user_id, budget_month, category_scope_key),
  KEY idx_finance_budget_user_month (user_id, budget_month),
  CONSTRAINT fk_finance_budget_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_finance_budget_category_user FOREIGN KEY (category_id, user_id) REFERENCES finance_categories (id, user_id),
  CONSTRAINT chk_finance_budget_limit CHECK (limit_cents >= 0)
);

CREATE TABLE finance_recurring_templates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  type TINYINT NOT NULL COMMENT '1 income, 2 expense',
  name VARCHAR(120) NOT NULL,
  amount_cents BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  frequency TINYINT NOT NULL COMMENT '0 monthly, 1 weekly',
  schedule_value TINYINT UNSIGNED NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uk_finance_recurring_template_id_user (id, user_id),
  KEY idx_finance_recurring_template_user (user_id, enabled),
  CONSTRAINT fk_finance_recurring_template_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_finance_recurring_template_account_user FOREIGN KEY (account_id, user_id) REFERENCES finance_accounts (id, user_id),
  CONSTRAINT fk_finance_recurring_template_category_user FOREIGN KEY (category_id, user_id) REFERENCES finance_categories (id, user_id),
  CONSTRAINT chk_finance_recurring_template_type CHECK (type IN (1, 2)),
  CONSTRAINT chk_finance_recurring_template_frequency CHECK (frequency IN (0, 1)),
  CONSTRAINT chk_finance_recurring_template_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE finance_recurring_occurrences (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  template_id BIGINT UNSIGNED NOT NULL,
  scheduled_date DATE NOT NULL,
  record_timezone VARCHAR(64) NOT NULL,
  status TINYINT NOT NULL DEFAULT 0 COMMENT '0 pending, 1 posted, 2 skipped',
  amount_cents_snapshot BIGINT UNSIGNED NOT NULL,
  account_id_snapshot BIGINT UNSIGNED NOT NULL,
  category_id_snapshot BIGINT UNSIGNED NOT NULL,
  posted_transaction_id BIGINT UNSIGNED NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uk_finance_recurring_occurrence_date (template_id, scheduled_date),
  KEY idx_finance_recurring_occurrence_user_status (user_id, status, scheduled_date),
  CONSTRAINT fk_finance_recurring_occurrence_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_finance_recurring_occurrence_template_user FOREIGN KEY (template_id, user_id) REFERENCES finance_recurring_templates (id, user_id),
  CONSTRAINT fk_finance_recurring_occurrence_transaction_user FOREIGN KEY (posted_transaction_id, user_id) REFERENCES finance_transactions (id, user_id),
  CONSTRAINT chk_finance_recurring_occurrence_status CHECK (status IN (0, 1, 2))
);
