import { type FormEvent, useState } from "react";
import { X } from "lucide-react";
import type { Request } from "../../app/api";
import { Button, IconButton } from "../../shared/ui";
import { accountTypeLabel, decimalToCents, type FinanceAccount, type FinanceCategory, type FinanceTransaction } from "./model";
import { tx } from "../../app/i18n";

export function TransactionActionDialog({ action, transaction, date, request, accounts, categories, onClose, onSaved, onError }: { action: "refund" | "correct"; transaction: FinanceTransaction; date: string; request: Request; accounts: FinanceAccount[]; categories: FinanceCategory[]; onClose: () => void; onSaved: () => Promise<void>; onError: (message: string, title?: string) => void }) {
  const availableAccounts = accounts.filter((item) => !item.archivedAt); const kind = transaction.type === "INCOME" ? "INCOME" : "EXPENSE"; const availableCategories = categories.filter((item) => item.kind === kind && item.enabled);
  const [draft, setDraft] = useState({ amount: "", accountId: String(transaction.accountId ?? availableAccounts[0]?.id ?? ""), categoryId: String(transaction.categoryId ?? availableCategories[0]?.id ?? ""), occurredDate: date, occurredTime: nowTime(), note: "" });
  const [pending, setPending] = useState(false); const [inlineError, setInlineError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setPending(true); setInlineError(null); try { const amountCents = decimalToCents(draft.amount); if (BigInt(amountCents) <= 0n) throw new Error(tx("金额必须大于 0")); const path = action === "refund" ? `/api/finance/transactions/${transaction.id}/refunds` : `/api/finance/transactions/${transaction.id}/correct`; await request(path, { method: "POST", body: JSON.stringify({ operationId: crypto.randomUUID(), expectedVersion: transaction.version, amountCents, accountId: Number(draft.accountId), ...(action === "correct" ? { categoryId: Number(draft.categoryId) } : {}), occurredDate: draft.occurredDate, occurredTime: draft.occurredTime, note: draft.note.trim() || null }) }); await onSaved(); onClose(); } catch (error) { const value = message(error); setInlineError(value); onError(value, action === "refund" ? tx("退款没有保存") : tx("更正没有保存")); } finally { setPending(false); } }
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form className="time-modal finance-dialog" onSubmit={submit}><header><div><p className="route-eyebrow">{tx("保留原始流水")}</p><h2>{action === "refund" ? tx("记录退款") : tx("更正流水")}</h2></div><IconButton label={tx("关闭")} type="button" onClick={onClose}><X size={17} /></IconButton></header><label className="finance-amount-field"><span>{action === "refund" ? tx("退款金额（元）") : tx("更正后金额（元）")}</span><div><b>¥</b><input autoFocus required inputMode="decimal" aria-label={tx("金额")} placeholder="0.00" value={draft.amount} onChange={(event) => setDraft({ ...draft, amount: event.target.value })} /></div></label><div className="finance-form-grid"><label>{tx("账户")}<select required className="field" value={draft.accountId} onChange={(event) => setDraft({ ...draft, accountId: event.target.value })}>{availableAccounts.map((item) => <option value={item.id} key={item.id}>{item.name} · {tx(accountTypeLabel[item.type])}</option>)}</select></label>{action === "correct" ? <label>{tx("分类")}<select required className="field" value={draft.categoryId} onChange={(event) => setDraft({ ...draft, categoryId: event.target.value })}>{availableCategories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label> : <span />}</div><div className="finance-form-grid"><label>{tx("发生日期")}<input required className="field" type="date" value={draft.occurredDate} onChange={(event) => setDraft({ ...draft, occurredDate: event.target.value })} /></label><label>{tx("发生时间")}<input required className="field" type="time" value={draft.occurredTime} onChange={(event) => setDraft({ ...draft, occurredTime: event.target.value })} /></label></div><label>{tx("备注")}<input className="field" maxLength={500} value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })} /></label>{inlineError ? <p className="notes-error" role="alert">{inlineError}</p> : null}<footer><Button type="button" onClick={onClose}>{tx("取消")}</Button><Button variant="primary" loading={pending} type="submit">{tx("保存")}{action === "refund" ? tx("退款") : tx("更正")}</Button></footer></form></div>;
}
function nowTime() { const now = new Date(); return `${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`; }
function message(error: unknown) { return error instanceof Error ? error.message : tx("操作失败"); }
