import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, BookOpenText, CalendarRange, ChevronRight, Clock3, Droplets, Moon, RefreshCw, Sparkles } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { Link } from "react-router";
import type { Request } from "../../app/api";
import { tx } from "../../app/i18n";
import { Badge, Button } from "../../shared/ui";

type DailyPayload = {
  businessDate: string;
  periodTimezone: string;
  tasks: { completed: Array<{ id: number; title: string }>; assignments: Array<{ id: number; title: string; completed: boolean; focusRank: number | null }> };
  actualTime: { totalMinutes: number; investment: Array<{ dimensionKey: string; name: string; color: string; minutes: number }>; unmappedMinutes: number };
  habits: { completed: number; items: Array<{ id: number; name: string; status: number }> };
  life: { sleep: { durationMinutes: number; qualityScore: number | null } | null; water: { cups: number; targetCups: number } | null; dailyStatus: { statusKey: string } | null };
  writing: { morningWritingSaved: boolean; journalSaved: boolean };
  rewards: { xpDelta: number; coinDelta: number };
};
type Snapshot = { id: number; businessDate: string; periodTimezone: string; sourceFingerprint: string; status: "CURRENT" | "STALE"; snapshotPayload: DailyPayload; version: number; generatedAt: string };
type PeriodFacts = { periodType: "WEEK" | "MONTH"; periodStart: string; periodEnd: string; periodTimezone: string; summary: { actualMinutes: number; completedTasks: number; completedHabits: number; sleepDays: number; waterCups: number; xpDelta: number }; growthDistribution: Array<{ dimensionKey: string; name: string; color: string; minutes: number }>; highlights: Array<{ businessDate: string; completedTasks: string[]; actualMinutes: number; completedHabits: number }> };
type Review = { id: number; periodType: "WEEK" | "MONTH"; periodStart: string; periodEnd: string; periodTimezone: string; sourceFingerprint: string; status: "CURRENT" | "STALE"; factsPayload: PeriodFacts; userReviewBody: string | null; version: number; generatedAt: string };

export function AdventureLogPage({ request, userId, date, onError }: { request: Request; userId: number; date: string; onError: (message: string, title?: string) => void }) {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["adventure-log", userId], queryFn: () => request<{ items: Snapshot[] }>("/api/adventure/snapshots") });
  const [pending, setPending] = useState(false);
  async function generate() { setPending(true); try { await request(`/api/adventure/snapshots/${date}/regenerate`, { method: "POST" }); await queryClient.invalidateQueries({ queryKey: ["adventure-log", userId] }); } catch (error) { onError(message(error), tx("冒险历程没有生成")); } finally { setPending(false); } }
  const items = query.data?.items ?? [];
  return <section className="adventure-log-route"><header className="adventure-log-head"><div><p className="route-eyebrow">Adventure Log</p><h1>{tx("冒险历程")}</h1><p>{tx("这里记录已经发生的事实，不读取私人文字正文。")}</p></div><div><Link className="ui-button ui-button-secondary ui-button-md" to={`/period-review?date=${date}`}><span className="ui-button-visual"><CalendarRange size={15} />{tx("周期复盘")}</span></Link><Button variant="primary" loading={pending} onClick={() => void generate()}><Sparkles size={15} />{tx("生成所选日期")}</Button></div></header>{query.isPending ? <p className="route-state">{tx("正在读取冒险历程...")}</p> : items.length ? <div className="adventure-log-list">{items.map((item) => { const facts = item.snapshotPayload; return <Link key={item.id} to={`/adventure-log/${item.businessDate}?date=${item.businessDate}`}><span className="adventure-log-date"><strong>{item.businessDate.slice(5)}</strong><small>{item.periodTimezone}</small></span><span className="adventure-log-summary"><strong>{facts.tasks.completed[0]?.title ?? tx("平静的一天")}</strong><small>{formatMinutes(facts.actualTime.totalMinutes)} · {tx("完成任务")} {facts.tasks.completed.length} · {tx("Habit 完成")} {facts.habits.completed}</small></span>{item.status === "STALE" ? <Badge tone="warning">{tx("需更新")}</Badge> : <Badge tone="success">{tx("已生成")}</Badge>}<ChevronRight size={17} /></Link>; })}</div> : <section className="adventure-empty"><BookOpenText size={28} /><h2>{tx("还没有冒险历程")}</h2><p>{tx("从所选日期生成第一份确定性记录。")}</p></section>}</section>;
}

export function AdventureLogDayPage({ request, userId, businessDate, onError }: { request: Request; userId: number; businessDate: string; onError: (message: string, title?: string) => void }) {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["adventure-log-day", userId, businessDate], queryFn: () => request<{ snapshot: Snapshot | null; stale: boolean }>(`/api/adventure/snapshots/${businessDate}`) });
  const [pending, setPending] = useState(false);
  async function regenerate() { setPending(true); try { await request(`/api/adventure/snapshots/${businessDate}/regenerate`, { method: "POST" }); await Promise.all([queryClient.invalidateQueries({ queryKey: ["adventure-log-day", userId, businessDate] }), queryClient.invalidateQueries({ queryKey: ["adventure-log", userId] })]); } catch (error) { onError(message(error), tx("冒险历程没有更新")); } finally { setPending(false); } }
  const snapshot = query.data?.snapshot;
  if (query.isPending) return <section className="adventure-log-route"><p className="route-state">{tx("正在读取冒险历程...")}</p></section>;
  if (!snapshot) return <section className="adventure-log-route"><header className="adventure-log-head"><div><p className="route-eyebrow">Adventure Log</p><h1>{businessDate}</h1></div><Button variant="primary" loading={pending} onClick={() => void regenerate()}>{tx("生成这一天")}</Button></header></section>;
  const facts = snapshot.snapshotPayload;
  const main = facts.tasks.assignments.filter((item) => item.focusRank !== null);
  const side = facts.tasks.assignments.filter((item) => item.focusRank === null);
  return <section className="adventure-log-route"><header className="adventure-log-head"><div><Link to="/adventure-log">{tx("冒险历程")}</Link><h1>{businessDate}</h1><p>{facts.periodTimezone} · fingerprint {snapshot.sourceFingerprint.slice(0, 10)}</p></div><Button loading={pending} onClick={() => void regenerate()}><RefreshCw size={15} />{query.data?.stale ? tx("事实已变化，重新生成") : tx("重新生成")}</Button></header>{query.data?.stale ? <div className="adventure-stale" role="status">{tx("源事实已经变化；当前版本已标记 stale。")}</div> : null}<div className="adventure-log-day-grid"><QuestGroup title={tx("Main Quest")} items={main} /><QuestGroup title={tx("Side Quest")} items={side} /><section className="adventure-day-panel"><h2>{tx("Daily Quest")}</h2>{facts.habits.items.length ? facts.habits.items.map((item) => <div key={item.id}><Activity size={15} /><span><strong>{item.name}</strong><small>{item.status === 1 ? tx("已完成") : tx("已记录")}</small></span></div>) : <p>{tx("这天没有 Habit occurrence。")}</p>}</section><section className="adventure-day-panel investment"><h2>{tx("Today Investment")}</h2><strong>{formatMinutes(facts.actualTime.totalMinutes)}</strong>{facts.actualTime.investment.map((item) => <div key={item.dimensionKey}><i style={{ background: item.color }} /><span>{item.name}</span><b>{formatMinutes(item.minutes)}</b></div>)}</section><section className="adventure-day-panel life"><h2>{tx("生活状态")}</h2><div><Moon size={15} /><span>{facts.life.sleep ? formatMinutes(facts.life.sleep.durationMinutes) : tx("未记录睡眠")}</span></div><div><Droplets size={15} /><span>{facts.life.water ? `${facts.life.water.cups}/${facts.life.water.targetCups}` : "0/8"}</span></div><div><Activity size={15} /><span>{facts.life.dailyStatus?.statusKey ?? tx("未自报状态")}</span></div></section><section className="adventure-day-panel gains"><h2>{tx("Notable Gains")}</h2><strong>+{facts.rewards.xpDelta} XP</strong><span>{tx("完成任务")} {facts.tasks.completed.length}</span><span>{tx("Habit 完成")} {facts.habits.completed}</span></section></div><footer className="adventure-journal-link"><span>{facts.writing.journalSaved ? tx("这天已有 Journal") : tx("这天尚未写 Journal")}</span><Link to={`/journal?date=${businessDate}&tab=journal`}>{facts.writing.journalSaved ? tx("打开 Journal") : tx("写下 Journal")}</Link></footer></section>;
}

function QuestGroup({ title, items }: { title: string; items: DailyPayload["tasks"]["assignments"] }) { return <section className="adventure-day-panel"><h2>{title}</h2>{items.length ? items.map((item) => <div key={item.id}><span><strong>{item.title}</strong><small>{item.completed ? tx("已完成") : tx("已接取")}</small></span></div>) : <p>{tx("没有记录")}</p>}</section>; }

export function PeriodReviewPage({ request, userId, date, onError }: { request: Request; userId: number; date: string; onError: (message: string, title?: string) => void }) {
  const queryClient = useQueryClient();
  const [type, setType] = useState<"WEEK" | "MONTH">("WEEK");
  const query = useQuery({ queryKey: ["period-review", userId, type, date], queryFn: () => request<{ review: Review | null; stale: boolean; facts: PeriodFacts }>(`/api/adventure/period-reviews?type=${type}&anchor=${date}`) });
  const [body, setBody] = useState("");
  const [pending, setPending] = useState(false);
  useEffect(() => { setBody(query.data?.review?.userReviewBody ?? ""); }, [query.data?.review?.id, query.data?.review?.version]);
  async function generate() { setPending(true); try { await request("/api/adventure/period-reviews/regenerate", { method: "POST", body: JSON.stringify({ type, anchor: date }) }); await queryClient.invalidateQueries({ queryKey: ["period-review", userId, type, date] }); } catch (error) { onError(message(error), tx("周期复盘没有生成")); } finally { setPending(false); } }
  async function save(event: FormEvent) { event.preventDefault(); const review = query.data?.review; if (!review) return; setPending(true); try { await request(`/api/adventure/period-reviews/${review.id}`, { method: "PUT", body: JSON.stringify({ expectedVersion: review.version, userReviewBody: body }) }); await queryClient.invalidateQueries({ queryKey: ["period-review", userId, type, date] }); } catch (error) { onError(message(error), tx("复盘正文没有保存")); } finally { setPending(false); } }
  const facts = query.data?.review?.factsPayload ?? query.data?.facts;
  return <section className="period-review-route"><header className="period-review-head"><div><p className="route-eyebrow">Period Review</p><h1>{tx("周期复盘")}</h1><p>{facts ? `${facts.periodStart} – ${facts.periodEnd}` : date}</p></div><div className="segmented-control" aria-label={tx("复盘周期")}><button className={type === "WEEK" ? "is-active" : ""} onClick={() => setType("WEEK")}>{tx("周复盘")}</button><button className={type === "MONTH" ? "is-active" : ""} onClick={() => setType("MONTH")}>{tx("月复盘")}</button></div></header>{facts ? <div className="period-review-facts"><span><Clock3 size={17} /><strong>{formatMinutes(facts.summary.actualMinutes)}</strong><small>{tx("实际投入")}</small></span><span><BookOpenText size={17} /><strong>{facts.summary.completedTasks}</strong><small>{tx("完成任务")}</small></span><span><Activity size={17} /><strong>{facts.summary.completedHabits}</strong><small>{tx("Habit 完成")}</small></span><span><Moon size={17} /><strong>{facts.summary.sleepDays}</strong><small>{tx("睡眠记录天数")}</small></span></div> : null}{query.data?.stale ? <div className="adventure-stale">{tx("期间事实已变化；重新生成不会覆盖你的正文。")}</div> : null}<section className="period-growth"><h2>{tx("成长投入分布")}</h2>{facts?.growthDistribution.length ? facts.growthDistribution.map((item) => <div key={item.dimensionKey}><i style={{ background: item.color }} /><span>{item.name}</span><strong>{formatMinutes(item.minutes)}</strong></div>) : <p>{tx("本期还没有实际投入。")}</p>}</section>{query.data?.review ? <form className="period-review-editor" onSubmit={save}><label>{tx("我的复盘")}<textarea value={body} maxLength={20000} onChange={(event) => setBody(event.target.value)} placeholder={tx("写下本期判断、变化与下一步...")} /></label><div><Button loading={pending} onClick={() => void generate()} type="button"><RefreshCw size={15} />{query.data.stale ? tx("更新确定性事实") : tx("重新生成事实")}</Button><Button variant="primary" loading={pending} type="submit">{tx("保存复盘")}</Button></div></form> : <section className="period-review-empty"><p>{tx("先生成确定性事实，再写下自己的复盘。")}</p><Button variant="primary" loading={pending} onClick={() => void generate()}>{tx("生成周期复盘")}</Button></section>}<p className="period-review-no-ai">{tx("V1 为确定性汇总，不依赖 AI。")}</p></section>;
}

function formatMinutes(minutes: number) { const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? rest ? `${hours}h ${rest}m` : `${hours}h` : `${minutes}m`; }
function message(error: unknown) { return error instanceof Error ? error.message : tx("操作失败"); }
