// @vitest-environment jsdom
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router";
import { afterEach, describe, expect, it, vi } from "vitest";
import type { Request } from "../../app/api";
import { GrowthPage, TodayGrowthEntry } from ".";
import { PIXEL_ASSET_MANIFEST } from "./pixel-assets";

afterEach(() => {
  cleanup();
  window.history.replaceState(null, "", "/");
});
const overview = { period: { days: 30, from: "2026-08-26", to: "2026-09-24", timezone: "Asia/Shanghai" }, hero: { level: 3, xpTotal: 400, coins: 27, xpInLevel: 150, xpForNextLevel: 450 }, summary: { actualMinutes: 600, mappedActualMinutes: 540, completedTaskCount: 4, habitCompletedCount: 3 }, dimensions: [{ id: 1, dimensionKey: "career", name: "事业", iconKey: "briefcase", color: "#5B8DEF", sortOrder: 10, actualMinutes: 360, share: 2 / 3, completedTaskCount: 3, lastActivityDate: "2026-09-23" }, { id: 2, dimensionKey: "learning", name: "学习", iconKey: "book-open", color: "#B28DFF", sortOrder: 20, actualMinutes: 180, share: 1 / 3, completedTaskCount: 1, lastActivityDate: "2026-09-22" }], unmapped: { actualMinutes: 60, completedTaskCount: 1, lastActivityDate: "2026-09-21" }, recent: [{ id: 1, kind: "TASK_COMPLETION" as const, businessDate: "2026-09-23", title: "完成 Growth V1", dimensionName: "事业", xpDelta: 20 }] };
const config = { dimensions: [{ id: 1, dimensionKey: "career", name: "事业", iconKey: "briefcase", color: "#5B8DEF", sortOrder: 10, enabled: 1, version: 1 }, { id: 2, dimensionKey: "learning", name: "学习", iconKey: "book-open", color: "#B28DFF", sortOrder: 20, enabled: 1, version: 1 }], categories: [{ id: 7, name: "工作", color: "#3B82F6", icon: "briefcase", dimensionKey: "career", enabled: 1 }, { id: 8, name: "其他", color: "#64748B", icon: "circle", dimensionKey: null, enabled: 0 }] };
function request(): Request { return vi.fn(async (path: string, init?: RequestInit) => { if (path.startsWith("/api/growth/overview")) return overview; if (path === "/api/growth/dimensions" && !init?.method) return config; if (init?.method) return {}; throw new Error(path); }) as Request; }
function wrapper(children: React.ReactNode) { return <QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><MemoryRouter>{children}</MemoryRouter></QueryClientProvider>; }

describe("Hero Growth V1", () => {
  it("renders hero XP, investment distribution, cards and visible unmapped attribution", async () => { render(wrapper(<GrowthPage request={request()} userId={1} date="2026-09-24" onError={vi.fn()} />)); expect(await screen.findByText("你的角色正在成长")).toBeTruthy(); expect(screen.getByText("Lv.3")).toBeTruthy(); expect(screen.getByText("经验 150/450")).toBeTruthy(); expect(screen.getByRole("heading", { name: "投入分布" })).toBeTruthy(); expect(screen.getByText("未映射")).toBeTruthy(); expect(screen.getByText(/按当前分类映射计算/)).toBeTruthy(); expect(screen.queryByText(/能力值/)).toBeNull(); });
  it("switches period, manages dimensions and maps categories through shared config", async () => { const api = request(); render(wrapper(<GrowthPage request={api} userId={1} date="2026-09-24" onError={vi.fn()} />)); await screen.findByText("你的角色正在成长"); fireEvent.click(screen.getByRole("button", { name: "7 天" })); await waitFor(() => expect((api as ReturnType<typeof vi.fn>).mock.calls.some(([path]) => path.includes("period=7"))).toBe(true)); fireEvent.click(await screen.findByRole("button", { name: "成长维度" })); expect((await screen.findAllByRole("button", { name: "停用" })).length).toBe(2); fireEvent.click(screen.getByRole("button", { name: "分类映射" })); fireEvent.change(await screen.findByLabelText("其他成长维度"), { target: { value: "learning" } }); await waitFor(() => expect(api).toHaveBeenCalledWith("/api/growth/category-mappings/8", { method: "PUT", body: JSON.stringify({ dimensionKey: "learning" }) })); });
  it("uses neutral same-size fallbacks and reserves pixel rendering slots", async () => { expect(PIXEL_ASSET_MANIFEST["hero-avatar"].src).toBe("/pixel/growth/hero-avatar@4x.png"); render(wrapper(<GrowthPage request={request()} userId={1} date="2026-09-24" onError={vi.fn()} />)); await screen.findByText("你的角色正在成长"); const slot = screen.getByLabelText("英雄半身像占位"); expect(slot.classList.contains("pixel-icon-slot")).toBe(true); const image = slot.querySelector("img")!; expect(image.classList.contains("pixel-image")).toBe(true); fireEvent.error(image); expect(slot.querySelector("img")).toBeNull(); expect(slot.querySelector("svg")).toBeTruthy(); });
  it("renders the compact Today entry without owning a second fact source", async () => { render(wrapper(<TodayGrowthEntry request={request()} userId={1} date="2026-09-24" />)); expect(await screen.findByText("Lv.3")).toBeTruthy(); expect(screen.getByText("本周投入 10h")).toBeTruthy(); expect(screen.getByRole("link", { name: "查看成长" }).getAttribute("href")).toBe("/growth?date=2026-09-24"); });
  it("shows a clear zero-data empty state without NaN", async () => { const emptyRequest = vi.fn(async (path: string) => path === "/api/growth/dimensions" ? config : { ...overview, summary: { actualMinutes: 0, mappedActualMinutes: 0, completedTaskCount: 0, habitCompletedCount: 0 }, dimensions: overview.dimensions.map((item) => ({ ...item, actualMinutes: 0, share: 0, completedTaskCount: 0, lastActivityDate: null })), unmapped: { actualMinutes: 0, completedTaskCount: 0, lastActivityDate: null }, recent: [] }) as Request; render(wrapper(<GrowthPage request={emptyRequest} userId={1} date="2026-09-24" onError={vi.fn()} />)); expect(await screen.findByText("还没有成长记录")).toBeTruthy(); expect(document.body.textContent).not.toContain("NaN"); });
});
